basePath: /
definitions:
  entity.Alert:
    properties:
      alert_id:
        description: Unique identifier for each alert
        type: integer
      alert_name:
        description: Name of the alert
        type: string
      create_at:
        description: Timestamp when the alert was created
        type: string
      description:
        description: Detailed description of the alert
        type: string
      ends_at:
        description: End time of the alert
        type: string
      generator_url:
        description: URL of the alert generator
        type: string
      instance:
        description: IP and port of the source
        type: string
      job:
        description: Job name, e.g., node_exporter, kafka_exporter
        type: string
      service:
        description: Arbitrary label for service, can be null
        type: string
      severity:
        description: Severity level of the alert
        type: string
      starts_at:
        description: Start time of the alert
        type: string
      status:
        description: Current status of the alert
        type: string
    type: object
  entity.Incident:
    properties:
      create_at:
        description: Timestamp when the incident was created
        type: string
      description:
        description: Detailed description of the incident
        type: string
      generator_url:
        description: URL of the incident generator
        type: string
      incident_id:
        description: Unique identifier for each incident
        type: integer
      severity_id:
        description: Level of criticality
        type: integer
      status_id:
        description: Current status of the incident
        type: integer
    type: object
  entity.IncidentState:
    properties:
      description:
        description: Detailed description of the state
        type: string
      id:
        description: Unique identifier for each state
        type: integer
      name:
        description: Name of the state
        type: string
    type: object
  entity.IntervalSetting:
    type: object
  entity.VMAlert:
    properties:
      annotations:
        additionalProperties:
          type: string
        type: object
      dashboardURL:
        type: string
      endsAt:
        type: string
      fingerprint:
        type: string
      generatorURL:
        type: string
      labels:
        additionalProperties:
          type: string
        type: object
      panelURL:
        type: string
      silenceURL:
        type: string
      startsAt:
        type: string
      status:
        type: string
      valueString:
        type: string
      values: {}
    type: object
  entity.VMAlertNotification:
    properties:
      alerts:
        items:
          $ref: '#/definitions/entity.VMAlert'
        type: array
      commonAnnotations:
        additionalProperties:
          type: string
        type: object
      commonLabels:
        additionalProperties:
          type: string
        type: object
      externalURL:
        type: string
      groupKey:
        type: string
      groupLabels:
        additionalProperties:
          type: string
        type: object
      message:
        type: string
      orgId:
        type: integer
      receiver:
        type: string
      state:
        type: string
      status:
        type: string
      title:
        type: string
      truncatedAlerts:
        type: integer
      version:
        type: string
    type: object
  v1.Status:
    properties:
      status:
        type: string
    type: object
host: localhost:8787
info:
  contact: {}
  description: AlertService
  termsOfService: http://swagger.io/terms/
  title: AlertService
  version: "1.0"
paths:
  /api/v1/alerts:
    get:
      description: Retrieve a list of alerts
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/entity.Alert'
            type: array
      summary: Get all alerts
      tags:
      - alerts
    post:
      consumes:
      - application/json
      description: ппринимает алерты от VM и сохраняет их в базу с дальнейшем уведомлением
      parameters:
      - description: уведомление об алертах
        in: body
        name: notification
        required: true
        schema:
          $ref: '#/definitions/entity.VMAlertNotification'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: int
      summary: принимает алерты от VM
      tags:
      - alerts
  /api/v1/alerts/{alert_id}:
    get:
      description: Retrieve an alert by its ID
      parameters:
      - description: Alert ID
        in: path
        name: alert_id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/entity.Alert'
      summary: Get alert by ID
      tags:
      - alerts
  /api/v1/alerts/list:
    get:
      description: Вернет список алертов отсортированных по времени начиная с begin
        в колличестве count
      parameters:
      - description: Starting alert index
        in: query
        name: begin
        required: true
        type: integer
      - description: Number of alerts
        in: query
        name: count
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/entity.Alert'
            type: array
      summary: Получение списка алертов
      tags:
      - alerts
  /api/v1/incident_states:
    get:
      description: Retrieve a list of alerts states
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/entity.IncidentState'
            type: array
      summary: Get all alerts
      tags:
      - state
  /api/v1/incidents:
    get:
      description: Retrieve a list of incidents
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/entity.Incident'
            type: array
      summary: Get all incidents
      tags:
      - incidents
  /api/v1/incidents/{incident_id}:
    get:
      description: Retrieve an incident by its ID
      parameters:
      - description: Incident ID
        in: path
        name: incident_id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/entity.Incident'
      summary: Get incident by ID
      tags:
      - incidents
    patch:
      description: Update an existing incident
      parameters:
      - description: Incident ID
        in: path
        name: incident_id
        required: true
        type: integer
      - description: New status
        in: body
        name: incident_status
        required: true
        schema:
          $ref: '#/definitions/v1.Status'
      responses:
        "204":
          description: No Content
      summary: Update an incident
      tags:
      - incidents
  /api/v1/settings/interval:
    get:
      description: Retrieve the current interval setting
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/entity.IntervalSetting'
      summary: Get interval setting
      tags:
      - settings
    post:
      consumes:
      - application/json
      description: Set a new interval setting
      parameters:
      - description: Interval Setting
        in: body
        name: interval
        required: true
        schema:
          $ref: '#/definitions/entity.IntervalSetting'
      produces:
      - application/json
      responses:
        "204":
          description: No Content
      summary: Set interval setting
      tags:
      - settings
swagger: "2.0"
