
ydb:
  # endpoint: "grpc://ydb.server.local:2135"
  connection_string: "grpc://localhost:2135/local"
  database: "/alert-db"
  # cert_path: "..."
  pool_size: 20
  timeout: 10

alert_statuses:
  statuses:
    - "Создано"
    - "В работе"
    - "Решено"
    - "Отклонено"