#!/bin/bash

set -e
#set -vx

ADMIN=" -x -D cn=admin,dc=example,dc=com -w admin_pass "

#slapcat -n 0 | grep olcModuleLoad

ldapadd $ADMIN <<EOF
dn: ou=policies,dc=example,dc=com
objectClass: organizationalUnit
objectClass: top
ou: policies
EOF

ldapadd -Q -Y EXTERNAL -H ldapi:/// <<EOF
dn: olcOverlay=ppolicy,olcDatabase={1}mdb,cn=config
changetype: add
objectClass: olcOverlayConfig
objectClass: olcPPolicyConfig
olcOverlay: ppolicy
olcPPolicyDefault: cn=default,ou=policies,dc=example,dc=com
olcPPolicyHashCleartext: FALSE
olcPPolicyForwardUpdates: FALSE
olcPPolicyUseLockout: FALSE
olcPPolicySendNetscapeControls: TRUE
EOF

ldapadd $ADMIN <<EOF
dn: cn=default,ou=policies,dc=example,dc=com
objectClass: organizationalRole
objectClass: pwdPolicy
cn: default
pwdAttribute: userPassword
pwdMaxAge: 1
pwdExpireWarning: 604801
pwdGraceAuthNLimit: 0
pwdFailureCountInterval: 0
pwdMaxFailure: 0
pwdLockout: TRUE
pwdMustChange: TRUE
pwdSafeModify: FALSE
EOF

#ldapsearch $ADMIN -b "cn=default,ou=policies,dc=example,dc=com" "(cn=default)"


#ldapmodify $ADMIN <<EOF
#dn: cn=default,ou=policies,dc=example,dc=com
#changetype: modify
#replace: pwdMaxAge
#pwdMaxAge: 1
#EOF
#
#ldapsearch $ADMIN -b "cn=default,ou=policies,dc=example,dc=com" "(cn=default)"

#ldapmodify -x -D "cn=admin,dc=example,dc=com" -w admin_pass <<EOF
#dn: uid=user123,ou=users,dc=example,dc=com
#changetype: modify
#replace: pwdLastSet
#pwdLastSet: 0
#EOF

# test user
#ldapsearch -x -D "uid=user123,ou=users,dc=example,dc=com" -w pass123 -b "dc=example,dc=com" "(uid=user123)"